backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Service Providers'
          name: "providers"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Organisation Type", name: "organisationType", widget: "text"}
            - { label: "Address", name: "address", widget: "map" }
            - { label: "Phone", name: "phone", widget: "number" }
            - { label: "Email", name: "email", widget: "string" }
            - { label: "Website", name: "website", widget: "string" }
            - { label: "Services", name: "offeredServices", widget: "text" }
            - { label: "Category", name: "category", widget: "list" }


