local_backend: true
backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
# File collections
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: Title, name: title, widget: string }
        - { label: Body, name: body, widget: markdown }
        - label: Categories
          name: categories
          widget: list
          fields:
            - { label: Name, name: name, widget: string }
            - { label: Description, name: description, widget: markdown }
            - { label: Service Providers, name: providers, widget: relation, collection: providers, search_fields: [ "name" ], value_field: name, multiple: true, min: 1 }

# Folder collections
  - name: "providers"
    label: "Service Providers"
    folder: "content/_providers"
    create: true
    identifier_field: name # this will be used instead of "title" for creating new entry slug
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Address", name: "address", widget: "string", required: false }
      - { label: "Phone", name: "phone", widget: "number", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Website", name: "website", widget: "string" }
      - { label: "Services", name: "offeredServices", widget: "text" }


